// src/redux/actionTypes/inventoryActionType/inventoryActionType.js
export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';


export const FETCH_UNIT_REQUEST = 'FETCH_UNIT_REQUEST';
export const FETCH_UNIT_SUCCESS = 'FETCH_UNIT_SUCCESS';
export const FETCH_UNIT_FAILURE = 'FETCH_UNIT_FAILURE';

export const FETCH_BRAND_REQUEST = 'FETCH_BRAND_REQUEST';
export const FETCH_BRAND_SUCCESS = 'FETCH_BRAND_SUCCESS';
export const FETCH_BRAND_FAILURE = 'FETCH_BRAND_FAILURE';

export const FETCH_MANUFACTURER_REQUEST = 'FETCH_MANUFACTURER_REQUEST';
export const FETCH_MANUFACTURER_SUCCESS = 'FETCH_MANUFACTURER_SUCCESS';
export const FETCH_MANUFACTURER_FAILURE = 'FETCH_MANUFACTURER_FAILURE';